[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "webstats_web"
version = "0.1.1"
description = "A web application to serve the content under www.bioconductor.org/packages/stats/"
authors = [{name = "Robert Shear"}, {name = "Nikhil Mane"}]
dependencies = [
    # Flask
    "click>=7.0",
    "Flask==2.3.3",
    "Werkzeug==2.3.7",

    # Database
    "Flask-SQLAlchemy==3.1.1",
    "psycopg2-binary==2.9.9",
    "SQLAlchemy==2.0.22",

    # Migrations
    "Flask-Migrate==4.0.5",

    # Forms
    "email-validator==2.0.0.post2",
    "Flask-WTF==1.2.1",
    "WTForms==3.1.0",

    # Deployment
    "gevent==23.9.1",
    "gunicorn>=19.9.0",
    "supervisor==4.2.5",

    # Flask Static Digest
    "Flask-Static-Digest==0.4.0",

    # Caching
    "Flask-Caching>=2.0.2",

    # Debug toolbar
    "Flask-DebugToolbar==0.13.1",

    # Environment variable parsing
    "environs==9.5.0",

    # App 
    "boto3",
    "chart.js",
]

[project.optional-dependencies]
dev = [

# Testing
    "factory-boy==3.3.0",
    "pytest==7.4.2",
    "pytest-cov==4.1.0",
    "WebTest==3.0.0",

# Lint and code style
    "black==23.10.0",
    "flake8-blind-except==0.2.1",
    "flake8-debugger==4.1.2",
    "flake8-docstrings==1.7.0",
    "flake8-isort==6.1.0",
    "flake8==6.1.0",
    "isort==5.12.0",
    "pep8-naming==0.13.3",
    "pytest-playwright",

# Local db manipulation
    "fastparquet"
]
[tool.setuptools.packages.find]
where = ["bioc_webstats"]

[tool.isort]
profile = "black"
skip_glob = ["migrations/*"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["bioc_webstats"]
