"""Initial migration

Revision ID: f4991b81f360
Revises: 
Create Date: 2024-01-07 06:12:00.187779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4991b81f360'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('packages_idx_lower_names', table_name='packages', postgresql_with={'deduplicate_items': 'false'})
    op.drop_index('packages_idx_package', table_name='packages', postgresql_with={'deduplicate_items': 'false'})
    op.drop_table('packages')
    op.drop_index('idx_date', table_name='bioc_web_downloads')
    op.drop_table('bioc_web_downloads')
    op.drop_table('webstats_info')
    op.drop_index('stats_idx_category', table_name='stats', postgresql_with={'deduplicate_items': 'true'})
    op.drop_table('stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('category', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('package', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_monthly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index('stats_idx_category', 'stats', ['category', 'package', 'date', 'is_monthly'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    op.create_table('webstats_info',
    sa.Column('key', sa.VARCHAR(length=23), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='webstats_info_pkey')
    )
    op.create_table('bioc_web_downloads',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('c-ip', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('sc-status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('package', sa.VARCHAR(length=64), autoincrement=False, nullable=True)
    )
    op.create_index('idx_date', 'bioc_web_downloads', ['date', 'c-ip', 'category', 'package'], unique=False)
    op.create_table('packages',
    sa.Column('category', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('package', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('first_version', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('last_version', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('lower_package', sa.VARCHAR(length=64), sa.Computed('lower((package)::text)', persisted=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category', 'package', name='packages_pkey')
    )
    op.create_index('packages_idx_package', 'packages', ['package'], unique=False, postgresql_with={'deduplicate_items': 'false'})
    op.create_index('packages_idx_lower_names', 'packages', ['lower_package'], unique=False, postgresql_with={'deduplicate_items': 'false'})
    # ### end Alembic commands ###
