"""empty message

Revision ID: 9c266b1a4aa9
Revises: 
Create Date: 2023-10-25 05:13:55.932899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c266b1a4aa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('category', sa.Enum('BIOC', 'EXPERIMENT', 'ANNOTATION', 'WORKFLOWS', name='packagetype'), nullable=False),
    sa.Column('package', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Dates repesenting months always have day=1, while years have month=12 and day=31'),
    sa.Column('is_monthly', sa.Boolean(), nullable=False, comment='If true, date span is 1 month, if false, 1 year'),
    sa.Column('ip_count', sa.BigInteger(), nullable=False),
    sa.Column('download_count', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('category', 'package', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
