---
- name: Install Python Packages and Apache
  hosts: ec2
  become: yes  # Use sudo to gain administrative privileges

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Ubuntu'  

    - name: Install system packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2

    - name: Install Python packages from dev.txt
      pip:
        requirements: /requirements/dev.txt