---
- name: Install Python packages on Ubuntu
  hosts: ec2
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - setuptools
        - python-dateutil
        - pandas
        - SQLAlchemy
        - pytest
        - Flask
        - Mock
        - syrupy
        - matplotlib
        - boto3
      register: package_installation_result

    - name: Display installed packages
      debug:
        var: package_installation_result
